name: Linting

on:
  - pull_request

jobs:
  lint:
    strategy:
      matrix:
        go-version:
          - 1.18.x
        os:
          - ubuntu-18.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Golint
        run: golint -set_exit_status ./...

